# lobby manager
# you can set this to true after you config the server; if you want.
hide-lobby-manager-command: false

# this section is used to manage /spawn command.
spawn-command-cool-down-in-sec: 1
should-afk-for-teleport: true
should-afk-admins-for-teleport: false

#    MINUTE,
#    HOUR,
#    DAY,
#    WEEK,
#    MONTH,
#    MANUAL
# this mean , when you set this value on any day. it counts from 1`st day of the month started.
# mean , when you config the lobbies in the middle of the year like jul 9. it calculates and save started day as jul 1 00:00AM ,this is for better rotation.
auto-rotate-lobbies-every: MANUAL

time-offset: 5.5

# SQL Support
use-sql: false
sql-host: localhost # database URL
sql-port: 3306
sql-database: lobby_player_db # database name
sql-username: user
sql-password: pass

